# Generated by Django 3.2.9 on 2021-12-06 14:57

from django.db import migrations, models
import recipes.validator


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=50, validators=[recipes.validator.validator_unit_of_measure]),
        ),
    ]
